# Generated by Django 5.1.2 on 2024-10-11 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogging', '0006_alter_comentario_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='visitas',
            field=models.IntegerField(default=0),
        ),
    ]
